# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AviationLonLatCalculator
                                 A QGIS plugin
 Calculates longitude, latitude for aviation data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-13
        copyright            : (C) 2021 by Paweł Strzelewicz
        email                : @
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AviationLonLatCalculator class from file AviationLonLatCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aviation_lon_lat_calculator import AviationLonLatCalculator
    return AviationLonLatCalculator(iface)
