# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AviationLonLatCalculator
                                 A QGIS plugin
 Calculates longitude, latitude for aviation data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Paweł Strzelewicz
        email                : @
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QWidget, QMessageBox
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .aviation_lon_lat_calculator_dialog import AviationLonLatCalculatorDialog
import os.path
from datetime import datetime
from functools import partial
from csv import DictReader


class AviationLonLatCalculator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self._output_layer = None
        self._output_layer_name = None
        self._provider = None
        self._feature = None
        self._point_calculation = None
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AviationLonLatCalculator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&AviationLonLatCalculator')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('AviationLonLatCalculator', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/aviation_lon_lat_calculator/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'AviationLonLatCalculator'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&AviationLonLatCalculator'),
                action)
            self.iface.removeToolBarIcon(action)

    def _clear_reference_point(self):
        """ Clear content of Reference point data. """
        self.dlg.lineEditReferenceID.clear()
        self.dlg.lineEditReferenceLongitude.clear()
        self.dlg.lineEditReferenceLatitude.clear()

    def _clear_polar_point_input(self):
        """ Clear content of Azimuth, distance (polar coordinates) single point mode data/settings. """
        self.dlg.lineEditPolarPointCalculatedPointID.clear()
        self.dlg.lineEditPolarPointDistanceValue.clear()
        self.dlg.lineEditPolarPointAzimuth.clear()
        self.dlg.comboBoxPolarPointDistanceUOM.setCurrentIndex(0)

    def _clear_ado_point_input(self):
        """ Clear content of Azimuth, distance, offset single point mode data/settings. """
        self.dlg.lineEditAdoPointCalculatedPointID.clear()
        self.dlg.lineEditAdoPointDistanceValue.clear()
        self.dlg.comboBoxAdoPointDistanceUOM.setCurrentIndex(0)
        self.dlg.lineEditAdoPointAzimuth.clear()
        self.dlg.comboBoxAdoPointOffsetSide.setCurrentIndex(0)
        self.dlg.lineEditAdoPointOffsetDistanceValue.clear()
        self.dlg.comboBoxAdoPointOffsetDistanceUOM.setCurrentIndex(0)

    def _clear_cartesian_point_input(self):
        """ Clear content of Cartesian point mode data/settings. """
        self.dlg.lineEditCartersianPointXAxisBearing.clear()
        self.dlg.comboBoxCartesianPointYAxisOrientation.setCurrentIndex(0)
        self.dlg.lineEditCartesianPointCalculatedPointID.clear()
        self.dlg.lineEditCartesianPointAxisXValue.clear()
        self.dlg.comboBoxCartesianPointAxisXUOM.setCurrentIndex(0)
        self.dlg.lineEditCartesianPointAxisYValue.clear()
        self.dlg.comboBoxCartesianPointAxisYUOM.setCurrentIndex(0)

    def _clear_polar_csv_input(self):
        """ Clear content of Azimuth, distance (polar coordinates) CSV mode data/settings. """
        self.dlg.comboBoxPolarCSVFieldCalculatedPointID.clear()
        self.dlg.comboBoxPolarCSVFieldDistanceValue.clear()
        self.dlg.comboBoxPolarCSVFieldDistanceUOM.clear()
        self.dlg.comboBoxPolarCSVFieldDistanceUOM.addItem('[user UOM]')
        self.dlg.comboBoxPolarCSVUserDistanceUOM.setEnabled(True)
        self.dlg.comboBoxPolarCSVUserDistanceUOM.setCurrentIndex(0)
        self.dlg.comboBoxPolarCSVFieldAzimuth.clear()

    def _clear_ado_csv_input(self):
        """ Clear content of Azimuth, distance, offset CSV mode data/settings. """
        self.dlg.comboBoxAdoCSVFieldCalculatedPointID.clear()
        self.dlg.comboBoxAdoCSVFieldDistanceValue.clear()
        self.dlg.comboBoxAdoCSVFieldDistanceUOM.clear()
        self.dlg.comboBoxAdoCSVFieldDistanceUOM.addItem('[user UOM]')
        self.dlg.comboBoxAdoUserDistanceUOM.setEnabled(True)
        self.dlg.comboBoxAdoUserDistanceUOM.setCurrentIndex(0)
        self.dlg.comboBoxAdoCSVFieldAzimuth.clear()
        self.dlg.comboBoxAdoCSVFieldOffsetSide.clear()
        self.dlg.comboBoxAdoCSVFieldOffsetDistanceValue.clear()
        self.dlg.comboBoxAdoCSVFieldOffsetDistanceUOM.clear()
        self.dlg.comboBoxAdoCSVFieldOffsetDistanceUOM.addItem('[user UOM]')
        self.dlg.comboBoxAdoUserOffsetDistanceUOM.setEnabled(True)
        self.dlg.comboBoxAdoUserOffsetDistanceUOM.setCurrentIndex(0)

    def _clear_cartesian_csv_input(self):
        """ Clear content of Cartesian CSV mode data/settings. """
        self.dlg.lineEditCartesianCSVAxisXBearing.clear()
        self.dlg.comboBoxCartesianCSVAxisYOrientation.setCurrentIndex(0)
        self.dlg.comboBoxCartesianCSVFieldCalculatedPointID.clear()
        self.dlg.comboBoxCartesianCSVFieldAxisXValue.clear()
        self.dlg.comboBoxCartesianCSVAxisXUOM.setCurrentIndex(0)
        self.dlg.comboBoxCartesianCSVFieldAxisYValue.clear()
        self.dlg.comboBoxCartesianCSVAxisYUOM.setCurrentIndex(0)

    def set_gui_default(self):
        """ Set initial values/settings of input data. Clear all input and set combobox items with current selection
        as first item on the combobox list. """
        self._clear_reference_point()
        self.dlg.comboBoxInputDataMode.setCurrentIndex(0)
        self.dlg.stackedWidgetInputData.setCurrentIndex(0)
        self.dlg.mQgsFileWidgetInputCSV.lineEdit().clear()
        self.dlg.labelInputCSV.setEnabled(False)
        self.dlg.mQgsFileWidgetInputCSV.setEnabled(False)
        self._clear_polar_point_input()
        self._clear_ado_point_input()
        self._clear_cartesian_point_input()
        self._clear_polar_csv_input()
        self._clear_ado_csv_input()
        self._clear_cartesian_csv_input()

    def _set_input_csv_field_mode(self):
        """ Enable/disable GUI element to select input CSV file if input data mode is one of related to CSVs. """
        if 3 <= self.dlg.comboBoxInputDataMode.currentIndex() <= 5:
            self.dlg.labelInputCSV.setEnabled(True)
            self.dlg.mQgsFileWidgetInputCSV.setEnabled(True)
        else:
            self.dlg.labelInputCSV.setEnabled(False)
            self.dlg.mQgsFileWidgetInputCSV.setEnabled(False)

    def switch_input_data_mode(self):
        """ Switch input data mode between different input: single point/CSV data, azimuth and distance etc.
        Note: Always 'clear' and set default values for user input data except reference point. """
        self.dlg.stackedWidgetInputData.setCurrentIndex(self.dlg.comboBoxInputDataMode.currentIndex())
        self.dlg.mQgsFileWidgetInputCSV.lineEdit().clear()
        self._set_input_csv_field_mode()
        self._clear_polar_point_input()
        self._clear_ado_point_input()
        self._clear_cartesian_point_input()
        self._clear_polar_csv_input()
        self._clear_ado_csv_input()
        self._clear_cartesian_csv_input()

    @staticmethod
    def _set_user_distance_uom_mode(field_widget, user_widget):
        """ Enable/disable combobox with user distance UOM (unit of measure),
        in case input CSV data does not contain distance UOM.
        Args:
            field_widget (): QComboBox, distance UOM from CSV field
            user_widget (): QComboBox,  distance UOM from user related to distance UOM from CSV field
        """
        user_widget.setEnabled(True) if field_widget.currentIndex() == 0 else user_widget.setEnabled(False)

    def get_csv_fields(self):
        if os.path.isfile(self.dlg.mQgsFileWidgetInputCSV.filePath()):
            with open(self.dlg.mQgsFileWidgetInputCSV.filePath(), 'r') as f:
                reader = DictReader(f, delimiter=';')
                return reader.fieldnames

    def _assign_polar_csv_fields(self, fields):
        """ Assign CSV fields from input CSV file.
        Args:
            fields (): list[str]
        """
        self.dlg.comboBoxPolarCSVFieldCalculatedPointID.addItems(fields)
        self.dlg.comboBoxPolarCSVFieldDistanceValue.addItems(fields)
        self.dlg.comboBoxPolarCSVFieldDistanceUOM.addItems(fields)
        self.dlg.comboBoxPolarCSVFieldAzimuth.addItems(fields)

    def _assign_ado_csv_fields(self, fields):
        """ Assign CSV fields from input CSV file.
        Args:
            fields (): list[str]
        """
        self.dlg.comboBoxAdoCSVFieldCalculatedPointID.addItems(fields)
        self.dlg.comboBoxAdoCSVFieldDistanceValue.addItems(fields)
        self.dlg.comboBoxAdoCSVFieldDistanceUOM.addItems(fields)
        self.dlg.comboBoxAdoCSVFieldAzimuth.addItems(fields)
        self.dlg.comboBoxAdoCSVFieldOffsetSide.addItems(fields)
        self.dlg.comboBoxAdoCSVFieldOffsetDistanceValue.addItems(fields)
        self.dlg.comboBoxAdoCSVFieldOffsetDistanceUOM.addItems(fields)

    def _assign_cartesian_csv_fields(self, fields):
        """ Assign CSV fields from input CSV file.
        Args:
            fields (): list[str]
        """
        self.dlg.comboBoxCartesianCSVFieldCalculatedPointID.addItems(fields)
        self.dlg.comboBoxCartesianCSVFieldAxisXValue.addItems(fields)
        self.dlg.comboBoxCartesianCSVFieldAxisYValue.addItems(fields)

    def reset_csv_fields_assignment(self):
        """ Reset CSV fields assignment for CSV mode calculations in case input CSV file has been changed. """
        fields = self.get_csv_fields()
        if fields:
            if self.dlg.stackedWidgetInputData.currentIndex() == 3:
                self._clear_polar_csv_input()
                self._assign_polar_csv_fields(fields)
            elif self.dlg.stackedWidgetInputData.currentIndex() == 4:
                self._clear_ado_csv_input()
                self._assign_ado_csv_fields(fields)
            elif self.dlg.stackedWidgetInputData.currentIndex() == 5:
                self.dlg.comboBoxCartesianCSVFieldAxisXValue.clear()
                self.dlg.comboBoxCartesianCSVFieldAxisYValue.clear()
                self._assign_cartesian_csv_fields(fields)

    # Output layer handling

    def _set_output_layer_name(self):
        """ Note: layer name is generated from timestamp. """
        timestamp = datetime.now()
        self._output_layer_name = "CalPoints_{}".format(timestamp.strftime("%Y_%m_%d_%H%M%f"))

    def is_output_layer_removed(self):
        """ Check if output layer has been removed from layers. """
        return not QgsProject.instance().mapLayersByName(self._output_layer_name)

    def create_output_layer(self):
        """ Create point layer to store calculated points.
        return: QgsVectorLayer
        """
        self._set_output_layer_name()
        self._output_layer = QgsVectorLayer('Point?crs=epsg:4326', self._output_layer_name, 'memory')
        self._provider = self._output_layer.dataProvider()
        self._output_layer.startEditing()
        self._provider.addAttributes([
            QgsField("POINT_ID", QVariant.String, len=100),
            QgsField("LON", QVariant.String, len=100),
            QgsField("LAT", QVariant.String, len=100),
            QgsField("POINT_DEF", QVariant.String, len=100),
        ])
        self._output_layer.commitChanges()
        self._feature = QgsFeature(self._output_layer.fields())
        QgsProject.instance().addMapLayer(self._output_layer)

    # Point(s) calculation

    def calculate(self):
        """ Calculate longitude, latitude based on input data. """
        if self.is_output_layer_removed():
            self.create_output_layer()

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = AviationLonLatCalculatorDialog()
            self.set_gui_default()
            self.dlg.comboBoxInputDataMode.currentIndexChanged.connect(self.switch_input_data_mode)
            self.dlg.pushButtonCalculate.clicked.connect(self.calculate)
            self.dlg.pushButtonCancel.clicked.connect(self.dlg.close)
            self.dlg.mQgsFileWidgetInputCSV.fileChanged.connect(self.reset_csv_fields_assignment)
            self.dlg.mQgsFileWidgetInputCSV.setFilter('*.csv')
            self.dlg.comboBoxPolarCSVFieldDistanceUOM.currentIndexChanged.connect(
                partial(self._set_user_distance_uom_mode,
                        field_widget=self.dlg.comboBoxPolarCSVFieldDistanceUOM,
                        user_widget=self.dlg.comboBoxPolarCSVUserDistanceUOM)
            )
            self.dlg.comboBoxAdoCSVFieldDistanceUOM.currentIndexChanged.connect(
                partial(self._set_user_distance_uom_mode,
                        field_widget=self.dlg.comboBoxAdoCSVFieldDistanceUOM,
                        user_widget=self.dlg.comboBoxAdoUserDistanceUOM))
            self.dlg.comboBoxAdoCSVFieldOffsetDistanceUOM.currentIndexChanged.connect(
                partial(self._set_user_distance_uom_mode,
                        field_widget=self.dlg.comboBoxAdoCSVFieldOffsetDistanceUOM,
                        user_widget=self.dlg.comboBoxAdoUserOffsetDistanceUOM))

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        self.set_gui_default()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
